apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/crossplane-providers'
    repoURL: 'https://github.com/twiessner/homelab-k8s-crossplane-argocd.git'
  project: default
  syncPolicy:
    automated:
      prune: true
